### ISSUE TITLE
Probleme beim Flashen eines Lolin D1 Mini Pro

### ISSUE THREAD

**Issue by moddmylife** [steff393/wbec#101]
Hallo,
wenn ich versuche über Plattformio einen D1 Mini Pro zu flashen (egal ob 0.5.0 oder 0.4.9), Startet dieser nach dem Flashen nicht. 
Nach dem errechnen und anpassen der Monitoring-Baudrate bekomme ich folgende anzeige:

rst cause 3, boot mode (3,6)
![image](https://github.com/steff393/wbec/assets/59995161/e3c0de28-4eea-44a7-8fc6-1085f7e5dd3a)

was könnte der grund sein? Env und Board habe ich angepasst.

`Processing d1_mini_pro (platform: espressif8266@4.0.1; board: d1_mini_pro; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini_pro.html
PLATFORM: Espressif 8266 (4.0.1) > WeMos D1 mini Pro
HARDWARE: ESP8266 80MHz, 80KB RAM, 16MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 3.30002.0 (3.0.2)
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30000.201119 (3.0.0)
 - toolchain-xtensa @ 2.100300.220621 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 47 compatible libraries
Scanning dependencies...
Dependency Graph
|-- modbus-esp8266 @ 4.1.0
|-- ESP Async WebServer @ 1.2.3
|-- ArduinoJson @ 6.21.3
|-- PubSubClient @ 2.8.0
|-- NTPClient @ 3.2.1
|-- MFRC522 @ 1.4.10
|-- RTCVars @ 0.1.1
|-- WebSockets @ 2.4.1
|-- AsyncElegantOTA @ 2.2.7
|-- Bounce2 @ 2.71.0
|-- LittleFS @ 0.1.0
|-- ESP8266mDNS @ 1.2
|-- ArduinoOTA @ 1.0
|-- WiFiManager-asyncwebserver
|-- EspSoftwareSerial @ 6.12.7
|-- ESP8266WiFi @ 1.0
|-- ESP8266HTTPClient @ 1.2
|-- SPI @ 1.0
|-- ESPAsyncTCP @ 1.2.2
Building in release mode
Compiling .pio\build\d1_mini_pro\src\button.cpp.o
Compiling .pio\build\d1_mini_pro\src\globalConfig.cpp.o
Compiling .pio\build\d1_mini_pro\src\goEmulator.cpp.o
Compiling .pio\build\d1_mini_pro\src\inverter.cpp.o
Compiling .pio\build\d1_mini_pro\src\loadManager.cpp.o
Compiling .pio\build\d1_mini_pro\src\logger.cpp.o
Compiling .pio\build\d1_mini_pro\src\main.cpp.o
Compiling .pio\build\d1_mini_pro\src\mbComm.cpp.o
Compiling .pio\build\d1_mini_pro\src\mqtt.cpp.o
Compiling .pio\build\d1_mini_pro\src\phaseCtrl.cpp.o
Compiling .pio\build\d1_mini_pro\src\powerfox.cpp.o
Compiling .pio\build\d1_mini_pro\src\pvAlgo.cpp.o
Compiling .pio\build\d1_mini_pro\src\rfid.cpp.o
Compiling .pio\build\d1_mini_pro\src\shelly.cpp.o
Compiling .pio\build\d1_mini_pro\src\webServer.cpp.o
Compiling .pio\build\d1_mini_pro\src\webSocket.cpp.o
Generating LD script .pio\build\d1_mini_pro\ld\local.eagle.app.v6.common.ld
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\BearSSLHelpers.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\CertStoreBearSSL.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\ESP8266WiFi.cpp.o
In file included from src\webServer.cpp:4:
.pio\libdeps\d1_mini_pro\AsyncElegantOTA\src/AsyncElegantOTA.h:4:2: warning: #warning AsyncElegantOTA.loop(); is deprecated, please remove it from loop() if defined. This function will be removed in a future release. [-Wcpp]
    4 | #warning AsyncElegantOTA.loop(); is deprecated, please remove it from loop() if defined. This function will be removed in a future release.
      |  ^~~~~~~
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\ESP8266WiFiAP.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\ESP8266WiFiGratuitous.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\ESP8266WiFiMulti.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\WiFiServer.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\WiFiUdp.cpp.o
Compiling .pio\build\d1_mini_pro\libe8c\ESP8266WiFi\enable_wifi_at_boot_time.cpp.o
Compiling .pio\build\d1_mini_pro\libb2d\modbus-esp8266\Modbus.cpp.o
Compiling .pio\build\d1_mini_pro\libb2d\modbus-esp8266\ModbusRTU.cpp.o
In file included from src\webServer.cpp:23:
.pio\libdeps\d1_mini_pro\ESP Async WebServer\src/SPIFFSEditor.h:16:101: warning: 'SPIFFS' is deprecated: SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems. [-Wdeprecated-declarations]
   16 |     SPIFFSEditor(const String& username=String(), const String& password=String(), const fs::FS& fs=SPIFFS);
      |                                                                                                     ^~~~~~
In file included from C:\Users\MKA\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/CertStoreBearSSL.h:26,
                 from C:\Users\MKA\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:30,
                 from C:\Users\MKA\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClientSecure.h:23,
                 from C:\Users\MKA\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,
                 from C:\Users\MKA\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,
                 from .pio\libdeps\d1_mini_pro\AsyncElegantOTA\src/AsyncElegantOTA.h:10,
                 from src\webServer.cpp:4:
C:\Users\MKA\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/FS.h:275:15: note: declared here
  275 | extern fs::FS SPIFFS __attribute__((deprecated("SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems.")));
      |               ^~~~~~
Compiling .pio\build\d1_mini_pro\lib34f\ESPAsyncTCP\AsyncPrinter.cpp.o
Compiling .pio\build\d1_mini_pro\lib34f\ESPAsyncTCP\ESPAsyncTCP.cpp.o
Compiling .pio\build\d1_mini_pro\lib34f\ESPAsyncTCP\ESPAsyncTCPbuffer.cpp.o
Compiling .pio\build\d1_mini_pro\lib34f\ESPAsyncTCP\SyncClient.cpp.o
Compiling .pio\build\d1_mini_pro\lib34f\ESPAsyncTCP\tcp_axtls.c.o
Compiling .pio\build\d1_mini_pro\lib2ee\Hash\Hash.cpp.o
Compiling .pio\build\d1_mini_pro\libc4d\ESP Async WebServer\AsyncEventSource.cpp.o
Compiling .pio\build\d1_mini_pro\libc4d\ESP Async WebServer\AsyncWebSocket.cpp.o
Compiling .pio\build\d1_mini_pro\libc4d\ESP Async WebServer\SPIFFSEditor.cpp.o
Archiving .pio\build\d1_mini_pro\libe8c\libESP8266WiFi.a
Compiling .pio\build\d1_mini_pro\libc4d\ESP Async WebServer\WebAuthentication.cpp.o
Archiving .pio\build\d1_mini_pro\libb2d\libmodbus-esp8266.a
Compiling .pio\build\d1_mini_pro\libc4d\ESP Async WebServer\WebHandlers.cpp.o
Compiling .pio\build\d1_mini_pro\libc4d\ESP Async WebServer\WebRequest.cpp.o
Compiling .pio\build\d1_mini_pro\libc4d\ESP Async WebServer\WebResponses.cpp.o
Compiling .pio\build\d1_mini_pro\libc4d\ESP Async WebServer\WebServer.cpp.o
Compiling .pio\build\d1_mini_pro\libf3a\PubSubClient\PubSubClient.cpp.o
Compiling .pio\build\d1_mini_pro\lib213\NTPClient\NTPClient.cpp.o
Archiving .pio\build\d1_mini_pro\lib2ee\libHash.a
Compiling .pio\build\d1_mini_pro\lib264\SPI\SPI.cpp.o
Archiving .pio\build\d1_mini_pro\lib34f\libESPAsyncTCP.a
Compiling .pio\build\d1_mini_pro\libabe\MFRC522\MFRC522.cpp.o
Compiling .pio\build\d1_mini_pro\libabe\MFRC522\MFRC522Extended.cpp.o
.pio\libdeps\d1_mini_pro\PubSubClient\src\PubSubClient.cpp: In member function 'boolean PubSubClient::publish_P(const char*, const uint8_t*, unsigned int, boolean)':
.pio\libdeps\d1_mini_pro\PubSubClient\src\PubSubClient.cpp:523:16: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
  523 |     return (rc == expectedLength);
      |             ~~~^~~~~~~~~~~~~~~~~
Archiving .pio\build\d1_mini_pro\libf3a\libPubSubClient.a
Archiving .pio\build\d1_mini_pro\lib213\libNTPClient.a
Compiling .pio\build\d1_mini_pro\libe42\RTCVars\RTCVars.cpp.o
Compiling .pio\build\d1_mini_pro\lib3e2\Ethernet\Dhcp.cpp.o
Archiving .pio\build\d1_mini_pro\lib264\libSPI.a
Compiling .pio\build\d1_mini_pro\lib3e2\Ethernet\Dns.cpp.o
Compiling .pio\build\d1_mini_pro\lib3e2\Ethernet\Ethernet.cpp.o
In file included from .pio\libdeps\d1_mini_pro\ESP Async WebServer\src\SPIFFSEditor.cpp:1:
.pio\libdeps\d1_mini_pro\ESP Async WebServer\src\SPIFFSEditor.h:16:101: warning: 'SPIFFS' is deprecated: SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems. [-Wdeprecated-declarations]
   16 |     SPIFFSEditor(const String& username=String(), const String& password=String(), const fs::FS& fs=SPIFFS);
      |                                                                                                     ^~~~~~
In file included from .pio\libdeps\d1_mini_pro\ESP Async WebServer\src/ESPAsyncWebServer.h:27,
                 from .pio\libdeps\d1_mini_pro\ESP Async WebServer\src\SPIFFSEditor.h:3,
                 from .pio\libdeps\d1_mini_pro\ESP Async WebServer\src\SPIFFSEditor.cpp:1:
C:\Users\MKA\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/FS.h:275:15: note: declared here
  275 | extern fs::FS SPIFFS __attribute__((deprecated("SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems.")));
      |               ^~~~~~
Archiving .pio\build\d1_mini_pro\libabe\libMFRC522.a
Compiling .pio\build\d1_mini_pro\lib3e2\Ethernet\EthernetClient.cpp.o
Compiling .pio\build\d1_mini_pro\lib3e2\Ethernet\EthernetServer.cpp.o
Archiving .pio\build\d1_mini_pro\libe42\libRTCVars.a
Compiling .pio\build\d1_mini_pro\lib3e2\Ethernet\EthernetUdp.cpp.o
Compiling .pio\build\d1_mini_pro\lib3e2\Ethernet\socket.cpp.o
Compiling .pio\build\d1_mini_pro\lib3e2\Ethernet\utility\w5100.cpp.o
Compiling .pio\build\d1_mini_pro\lib73b\WebSockets\SocketIOclient.cpp.o
Compiling .pio\build\d1_mini_pro\lib73b\WebSockets\WebSockets.cpp.o
Compiling .pio\build\d1_mini_pro\lib73b\WebSockets\WebSocketsClient.cpp.o
Compiling .pio\build\d1_mini_pro\lib73b\WebSockets\WebSocketsServer.cpp.o
Compiling .pio\build\d1_mini_pro\lib73b\WebSockets\libb64\cdecode.c.o
Compiling .pio\build\d1_mini_pro\lib73b\WebSockets\libb64\cencode.c.o
Compiling .pio\build\d1_mini_pro\lib73b\WebSockets\libsha1\libsha1.c.o
Compiling .pio\build\d1_mini_pro\lib227\Bounce2\Bounce2.cpp.o
Compiling .pio\build\d1_mini_pro\lib762\LittleFS\LittleFS.cpp.o
Compiling .pio\build\d1_mini_pro\lib762\LittleFS\lfs.c.o
Compiling .pio\build\d1_mini_pro\lib762\LittleFS\lfs_util.c.o
Compiling .pio\build\d1_mini_pro\lib161\ESP8266mDNS\ESP8266mDNS.cpp.o
Compiling .pio\build\d1_mini_pro\lib161\ESP8266mDNS\LEAmDNS.cpp.o
Compiling .pio\build\d1_mini_pro\lib161\ESP8266mDNS\LEAmDNS_Control.cpp.o
Archiving .pio\build\d1_mini_pro\lib3e2\libEthernet.a
Compiling .pio\build\d1_mini_pro\lib161\ESP8266mDNS\LEAmDNS_Helpers.cpp.o
Compiling .pio\build\d1_mini_pro\lib161\ESP8266mDNS\LEAmDNS_Structs.cpp.o
Archiving .pio\build\d1_mini_pro\lib227\libBounce2.a
Compiling .pio\build\d1_mini_pro\lib161\ESP8266mDNS\LEAmDNS_Transfer.cpp.o
Compiling .pio\build\d1_mini_pro\liba0c\ArduinoOTA\ArduinoOTA.cpp.o
Compiling .pio\build\d1_mini_pro\libf82\DNSServer\DNSServer.cpp.o
Compiling .pio\build\d1_mini_pro\libe25\ESP8266WebServer\detail\mimetable.cpp.o
Archiving .pio\build\d1_mini_pro\libc4d\libESP Async WebServer.a
Archiving .pio\build\d1_mini_pro\lib73b\libWebSockets.a
Compiling .pio\build\d1_mini_pro\libcc7\WiFiManager-asyncwebserver\WiFiManager.cpp.o
Archiving .pio\build\d1_mini_pro\lib762\libLittleFS.a
Compiling .pio\build\d1_mini_pro\lib19e\SoftwareSerial\SoftwareSerial.cpp.o
Compiling .pio\build\d1_mini_pro\lib959\ESP8266HTTPClient\ESP8266HTTPClient.cpp.o
Archiving .pio\build\d1_mini_pro\libe25\libESP8266WebServer.a
Archiving .pio\build\d1_mini_pro\libFrameworkArduinoVariant.a
Compiling .pio\build\d1_mini_pro\FrameworkArduino\Crypto.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\Esp-frag.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\Esp-version.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\Esp.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\FS.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\FSnoop.cpp.o
Archiving .pio\build\d1_mini_pro\libf82\libDNSServer.a
Compiling .pio\build\d1_mini_pro\FrameworkArduino\FunctionalInterrupt.cpp.o
Archiving .pio\build\d1_mini_pro\lib161\libESP8266mDNS.a
Compiling .pio\build\d1_mini_pro\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\IPAddress.cpp.o
Archiving .pio\build\d1_mini_pro\liba0c\libArduinoOTA.a
Archiving .pio\build\d1_mini_pro\lib19e\libSoftwareSerial.a
Compiling .pio\build\d1_mini_pro\FrameworkArduino\LwipDhcpServer-NonOS.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\LwipDhcpServer.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\LwipIntf.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\LwipIntfCB.cpp.o
Archiving .pio\build\d1_mini_pro\lib959\libESP8266HTTPClient.a
Compiling .pio\build\d1_mini_pro\FrameworkArduino\MD5Builder.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\Print.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\Schedule.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\StackThunk.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\StreamSend.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\Tone.cpp.o
Archiving .pio\build\d1_mini_pro\libcc7\libWiFiManager-asyncwebserver.a
Compiling .pio\build\d1_mini_pro\FrameworkArduino\TypeConversion.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\Updater.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\WString.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\abi.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\aes_unwrap.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\base64.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\cont.S.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\cont_util.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_app_entry_noextra4k.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_eboot_command.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_features.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_flash_quirks.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_flash_utils.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_i2s.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_main.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_non32xfer.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_noniso.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_phy.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_postmortem.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_si2c.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_sigma_delta.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_spi_utils.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_timer.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_vm.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_waveform_phase.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_waveform_pwm.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_wiring.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_wiring_analog.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_wiring_digital.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_wiring_pulse.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_wiring_pwm.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\core_esp8266_wiring_shift.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\crc32.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\debug.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\exc-c-wrapper-handler.S.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\exc-sethandler.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\flash_hal.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\gdb_hooks.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\heap.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\hwdt_app_entry.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\libb64\cdecode.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\libb64\cencode.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\libc_replacements.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\mmu_iram.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\reboot_uart_dwnld.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\spiffs\spiffs_cache.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\spiffs\spiffs_check.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\spiffs\spiffs_gc.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\spiffs\spiffs_hydrogen.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\spiffs\spiffs_nucleus.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\spiffs_api.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\sqrt32.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\stdlib_noniso.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\time.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\uart.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\umm_malloc\umm_info.c.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\umm_malloc\umm_integrity.c.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\umm_malloc\umm_local.c.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\umm_malloc\umm_malloc.cpp.o
Compiling .pio\build\d1_mini_pro\FrameworkArduino\umm_malloc\umm_poison.c.o
C:\Users\MKA\.platformio\packages\framework-arduinoespressif8266\cores\esp8266\mmu_iram.cpp:26:34: note: '#pragma message: ICACHE size 16K'
   26 | #pragma message("ICACHE size 16K")
      |                                  ^
Archiving .pio\build\d1_mini_pro\libFrameworkArduino.a
Linking .pio\build\d1_mini_pro\firmware.elf
Retrieving maximum program size .pio\build\d1_mini_pro\firmware.elf
Checking size .pio\build\d1_mini_pro\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=======   ]  66.9% (used 54784 bytes from 81920 bytes)
Flash: [========  ]  83.1% (used 867852 bytes from 1044464 bytes)
Building .pio\build\d1_mini_pro\firmware.bin
Creating BIN file ".pio\build\d1_mini_pro\firmware.bin" using "C:\Users\MKA\.platformio\packages\framework-arduinoespressif8266\bootloaders\eboot\eboot.elf" and ".pio\build\d1_mini_pro\firmware.elf"
========================================================================================= [SUCCESS] Took 81.88 seconds =========================================================================================
 *  Terminal will be reused by tasks, press any key to close it. 
`

Irgendwelche Ideen?

**Comment by steff393** [comment]
wbec ist nicht für den D1 Mini Pro ausgelegt.

**Comment by joschro** [comment]
die wbec Firmware läuft bei mir auf einem Wemos D1 Mini Pro anstandslos. Versuch's mal mit der fertigen Firmware von Stefan und z.B. dem esptool:
esptool --port /dev/ttyUSB0 --baud 115200 write_flash --flash_size=4MB -fm dio 0 wbec_firmware_0_5_3.bin
(unter Linux bei mir, evt. ist bei Dir der Port ein anderer)
