### ISSUE TITLE
Web Interface nicht erreichbar

### ISSUE THREAD

**Issue by weissjuergen** [steff393/wbec#104]
Es kommt immer wieder vor dass der WBECPro manchmal nicht erreichbar ist und sich das auch nicht mehr ändert, bis man die 12V Stromversorgung kurz entfernt. Da bei mir alles in der Wallbox integriert ist muss ich leider die Sicherung der Wallbox ab- und anschalten. In dieser Zeit stellt das Gerät auch kein eigenes WLAN zur Verfügung. Passiert so einmal in der Woche bei mir. Gibt es eine einfache Möglichkeit das Interface 1 mal zu einer festen Zeit neu zu starten ?

**Comment by steff393** [comment]
Hallo Jürgen,
in der Wallbox ist durch das Metallgehäuse und die dicken Kabel meist das WLAN recht schlecht. Es gibt einen Parameter cfgKnockOutTimer. Hier kann man z.B. alle 1440 Minuten einen Reset auslösen, das wäre dann einmal pro Tag.
