### ISSUE TITLE
Webinterface: Ladeleistung wird bei einphasigem Betrieb am Slider Ladestrom falsch angezeigt

### ISSUE THREAD

**Issue by h202-ing** [steff393/wbec#108]
Hi,
Im Webinterface scheint die Ladeleistung am Slider für Ladestrom falsch berechnet oder angezeigt zu werden. Dies scheint nur im einphasigem Betrieb der Fall zu sein. Siehe Screenshot.

![image](https://github.com/steff393/wbec/assets/125375173/7c3c7cec-7a14-4cdb-ad27-34eb2f6951c0)

cfgPvPhFactor wurde auf einphasigen Betrieb konfiguriert.
![image](https://github.com/steff393/wbec/assets/125375173/730f92f7-48c1-4351-b3ae-c2e696e238db)

Meine Vermutung dazu (nicht getestet) ist, dass in der web.js der Wert für "phases" hart auf "3" gesetzt wird.

`window.addEventListener('DOMContentLoaded', () => {
	// Adjustable values -----
	let phases         = 3;   // number of phases`

Nix weltbewegendes, aber ich dachte, ich lasse den Hinweis mal da.

**Comment by steff393** [comment]
Ja, das ist so gedacht, dass man sich den Wert einstellen kann. Einfach von 3 auf 1 oder 2 ändern.
