### ISSUE TITLE
Router tausch - Wlan neu einrichten ?

### ISSUE THREAD

**Issue by csh-de** [steff393/wbec#109]
Hallo,

bei mir steht ein Router tausch an und neues WLAN, wo kann ich das am einfachsten ändern?
Im Moment laufen beide aber auf wbec.local sehe ich keine Möglichkeit zum Wlan ändern?

**Comment by hawa-lc4** [comment]
Hallo,
im graphischen User Interface ist diese Funktion nicht integriert.
Zuerst unbedingt die Config-Einstellungen im GUI zu "cfgApSsid" und "cfgApPass" genau notieren.
Durch Aufruf der Adresse  wbec.local/resetwifi  können die derzeitigen WiFi Einträge gelöscht werden, wbec startet dann im Station-Mode mit den vorhin notierten Einstellungen für die SSID und das Passwort.
Auf dieses WLAN verbindet man sich dann am besten mit einem mobile-device und die Konfiguration läuft dann wie bei einer Erstinstallation ab.
Aufruf der Adresse 192.168.4.1 mit dem Browser des mobile-device und dann die wbec WiFi Konfiguration durchführen.

hth.
