### ISSUE TITLE
Getting started guide?

### ISSUE THREAD

**Issue by matzetronic** [steff393/wbec#11]
Hi,
ich vermisse noch einen getting started guide für das Projekt, oder hab ich den übersehen? 🤔
- Welche Hardware brauche ich (außer dem ESP8266) und wo bekomme ich die her?
- Wie bekomme ich die Software auf den ESP8266?

Wäre klasse wenn du noch sowas in die Readme oder Wiki aufnehmen könntest, danke!

**Comment by steff393** [comment]
Hi matzetronic, bitte schreib mir kurz per Mail an wbec393@gmail.com, danke!
