### ISSUE TITLE
Feature request / heads up

### ISSUE THREAD

**Issue by hawa-lc4** [steff393/wbec#111]
Vor längerer Zeit tauchte das Problem auf das mit platform espressif8266@4.1.0 und höher Abstürze der MCU beim Zugriff auf die Web-Seiten auftraten. Das wurde behoben durch eine feste Zuordnung der platform espressif8266@4.0.1.

Weiter beobachte ich seit längerem in verschiedenen Projekten Probleme mit AsyncElegantOTA version 2.2.7 und 2.2.8 die auf den hier dokumentierten Fehler (https://github.com/ayushsharma82/ElegantOTA/issues/67) zurückzuführen sind. Die einzige Abhilfe war die Version fest auf die 2.2.5 einzustellen. Die Fehlerdokumentation ist zwar für ElegantOTA (also nicht die Async Variante) das Fehlerbild ist aber 100% identisch.
In ElegantOTA wurde der Fehler mit der 2.2.8 gefixt, der Fix taucht aber nicht in der 2.2.8 von AsyncElegantOTA auf.
Seit kurzem ist AsyncElegantOTA  als "depricated" markiert und wird nicht weiter gepflegt.

Auf der Basis von wbec 0.5.0 habe ich seit längerem meine Installation am Laufen mit der platform espressif8266@4.2.1 und dem Nachfolgeprojekt von AsyncElegantOTA :  ElegantOTA 3.1.0 welches auch einen Async-Modus anbietet durch setzen des Compiler Parameters "ELEGANTOTA_USE_ASYNC_WEBSERVER=1".
Meine wbec läuft zusammen mit dem wbec-0.5.0_data_fix nun seit 14 Tagen problemlos und ohne Abstürze auch bei Zugriffen auf die Web-Seiten. Das neue ElegantOTA hat nur ein komplett neues UI, sonst ist alles wie gehabt.
Änderungen in den anderen Komponenten von wbec, besonders dem WiFiManager-asyncwebserver, sind soweit ich erkennen kann nicht erforderlich.

Das alles nur als Info für weitere Planungen.
hth.

**Comment by steff393** [comment]
Danke für die Info! Das ist eine gute Idee und ich bin jetzt dennoch zu dem Schluss gekommen, dass ich es aktuell noch nicht ändere (eher aus einer "Never touch a running system"-Denke heraus). Vielleicht aber zukünftig mal.
