### ISSUE TITLE
LOG funktioniert nicht

### ISSUE THREAD

**Issue by BlackandGold1** [steff393/wbec#114]
Was genau muss ich einstellen damit ich was in der Ladeübersicht sehe?  Wbec 0.5.1

**Comment by steff393** [comment]
Das Ladelog funktioniert leider nur mit wbecPro, wbecLan oder wbecPremium (also 1.5.1 oder 2.5.1)

**Comment by snowy-18** [comment]
Hallo Stefan, ich hänge mich mal hier dran.
Mein wbecPremium hat ein Jahr lang darauf gewartet angeschlossen zu werden - vor ein paar Wochen bin ich endlich dazu gekommen und alles läuft wunderbar, außer der Ladelog. 
Habe mit 1.5.1 begonnen und bin mittlerweile auf 1.5.2, die Daten des Energiezählers passen, aber der Log bleibt leer.
Hast du eine Idee woran das liegen könnte?

**Comment by steff393** [comment]
Hi, hast du 
cfgChargeLog           :"Logbuch der Ladevorgänge: 0:inaktiv, 1:aktiv"
auf 1 gesetzt (und danach einen Reset von wbec durchgeführt)?

**Comment by snowy-18** [comment]
Der Wald und die Bäume und so. Danke!
