### ISSUE TITLE
WBEC box not constantly available after upgrade to 0.41

### ISSUE THREAD

**Issue by oldgitdaddy** [steff393/wbec#12]
After upgrade and reset, the availbility of wbec is really limited. It got even worse. Ping to wbec is also loosing packages. Any advice is appreciated. Do other users have a similar impression regarding the stability after the upgrade?

Cheers!

**Comment by steff393** [comment]
wbec 0.4.2 will have an optional parameter cfgWifiSleepMode:
"cfgWifiSleepMode":0  => WIFI_NONE_SLEEP
"cfgWifiSleepMode":1  => WIFI_LIGHT_SLEEP
"cfgWifiSleepMode":2  => WIFI_MODEM_SLEEP
If it has a different value or is not set at all, then there's no change (i.e. WiFi.setSleepMode() is then not called).

**Comment by oldgitdaddy** [comment]
I have installed now version 0.4.2. Will report on the long-term behavior of wbec, but until now it is looking well.

You may consider to update the wiki regarding the additional configuration.

Let´s close the discussion here then.
