### ISSUE TITLE
Difficult to set the max. charge current to 6 Ampere

### ISSUE THREAD

**Issue by kalwados** [steff393/wbec#121]
I find it very difficult to set the charge current slider to 6 A, because the slider jumps from 6 A to Zero. With some modifications to web.js this problem can be solved; patch attached,
[web.js.patch](https://github.com/steff393/wbec/files/14396492/web.js.patch)

**Comment by steff393** [comment]
Thanks, will be implemented, but I'd propose the following form:
```
if ((val >= 0) && (val <= 30)) {
	elementCurrentSlider.value = val = 0;
}
if ((val > 30) && (val <= 60)) {
	elementCurrentSlider.value = val = 60;
}
```
