### ISSUE TITLE
Wifi-Einstellungen und Ladestrom nach Stromausfall zurückgesetzt

### ISSUE THREAD

**Issue by davull** [steff393/wbec#124]
Guten Tag,

zu Beginn möchte ich dir für deine Arbeit an diesem Projekt danken :)

Ich habe eine wbecPro (Software 1.5.0) an einer Heidelberg Energy Control und habe das Problem, dass nach einem Stromausfall bzw. Stecker ziehen sich die wbec nicht mehr mit dem zuvor konfigurierten WLAN verbindet. Stattdessen wird sofort das Adhoc-WLAN aufgespannt.
Die Einstellung `cfgWifiConnectTimeout` habe ich auf 600 [s] gesetzt.

Zudem ist nach dem Neustart (nach Konfiguration des WLANs) die Ladeleistung auf 0 gesetzt, so dass man hier wieder den gewünschten Wert einstellen muss.

Werden diese Einstellungen nicht persistiert? Gibt es eine Möglichkeit, dass auch nach einem Neustart (nach stromlos) der Wallbox und/oder der wbec einfach die zuvor getätigte Konfiguration (vor allem für WLAN) greift?

Gruß
David

**Comment by steff393** [comment]
Hallo David,

doch, die WLAN-Einstellungen (SSID und Passwort) werden schon persistent gespeichert. Wenn dieses WLAN nicht erreichbar ist, wird das "wbec"-Netzwerk aufgespannt.

Die Ladeleistung wird nicht in wbec selbst, sondern in der Wallbox gespeichert und nach Start oder Reset von wbec ausgelesen. Wenn die Funktion "Standby" in der Wallbox aktiviert ist, führt dies jedoch dazu, dass die Wallbox bei einem Neustart oder Wakeup (der Wallbox) den Default-Wert (0A) einstellt.
