### ISSUE TITLE
wbec keine Verbindung möglich

### ISSUE THREAD

**Issue by csh-de** [steff393/wbec#127]
keine Verbindung möglich, es kommt immer

Die Website ist nicht erreichbar 
192.168.178.25 hat die Verbindung abgelehnt.

warum passiert das? Warum lehnt er Verbindungen ab?
Ping geht aber das web Interface geht nicht auf.
Ping hat 4ms und Signal ist bei 90%, wenn ich wlan reset mache und neu einrichte, aber komme nicht mehr auf die Web interface.

**Comment by steff393** [comment]
s. Issue #99

**Comment by abuesen** [comment]
> keine Verbindung möglich, es kommt immer
> 
> Die Website ist nicht erreichbar 192.168.178.25 hat die Verbindung abgelehnt.
> 
> warum passiert das? Warum lehnt er Verbindungen ab? 

Wie schon geschrieben wahrscheinlich issue 99, ein zu viel für den ESP. Es tritt hauptsächlich mit Mobilgeräten, auf. Vom PC sollte funktionieren.
