### ISSUE TITLE
per Befehl standby?

### ISSUE THREAD

**Issue by csh-de** [steff393/wbec#128]
ist es möglich den standby nur einmal am tag zb 22uhr an zu machen damit der Energiezähler gespeichert wird und nicht verloren geht?

Hintergrund ist:
Lasse ich die standby Funktion auf an dann reagieren meine abfragen manchmal nicht und Grafana zeigt nix an.
Lasse ich standby aus, geht alles perfekt, aber bei einem Stromausfall ist der Energie Zahler weg...

**Comment by steff393** [comment]
s. #129, technisch nicht umsetzbar, nach Standby ist die Box nicht mehr erreichbar.
