### ISSUE TITLE
cfgEnergyOffset | keine Veränderung bei den Werten

### ISSUE THREAD

**Issue by Heino1988** [steff393/wbec#129]
Hallo 
bei mir hängt sich die Wallbox sporadisch auf, sodass sie blau blinkt und erst durch eine komplette Kappung der Stromversorgung wieder in den regulären Modus kommt.

Dabei ist mir am Energiezähler aufgefallen, dass dieser um eine gewisse, teilweise sehr hohe, Strommenge zurückgesetzt wird - siehe Datenbank-Grafik.
![2024-04-11 17_27_59-Window](https://github.com/steff393/wbec/assets/106521143/6aa861ad-64e1-4ab3-a75f-4044a605e1b6)

Da ich damit auch eine Stromaufstellung für meine Firma mache, würde ich gerne diese Strommenge über den cfgEnergyOffset wieder hinzuaddieren.
Weder ein positiver, noch ein negativer Wert in den Configs ändert bei mir etwas an der Energiemenge.

Ist das nur bei mir so bzw. kann ich das Thema mit #128 zusammenlegen?

Danke und Grüße
Heino

**Comment by abuesen** [comment]
Hallo Heino,

aus dem https://github.com/steff393/wbec/issues/128 habe ich auch gelernt, dass der Zähler nur beim Übergang in _Standby_ gespeichert wird. Sehr doof.  Ich habe auch einen eigenen Zähler davor. Deine Frage kann ich nicht beantworten.

Es wäre aber vielleicht eine Idee, für Grafana die einzelnen Ladevorgänge anstatt der Gesamtmenge zu speichern. Also möglichst das Delta pro Zeiteinheit. Damit kann man alle späteren Fragestellungen auch wieder herstellen. Auch mit dem Offset würde dem Zähler der HDEC im absoluten Wert nicht annähernd vertrauen. Die Deltas dürften statistisch deutlich zuverlässigere Werte erzeugen.

Wenn es für eine Abrechnungen verwendet wird muss eh ein geeichter MIT-Zähler daher. Kostet etwa 60,- plus Einbau.

LG, A.

**Comment by csh-de** [comment]
ja das hängt mit dem Standby zusammen..
die Info hatte ich vom Entwickler bekommen, da ich es mir erst nicht erklären konnte.. 

also lieber mit Standby arbeiten dann sind die Werte nicht weg...

**Comment by Heino1988** [comment]
> also lieber mit Standby arbeiten dann sind die Werte nicht weg...

Wo und wie kann ich das aktiv ansteuern?

**Comment by csh-de** [comment]
![b8a637c2-51de-4ed1-94f2-58c2496d68b9](https://github.com/steff393/wbec/assets/130899114/400e1b79-cbf3-4499-b12d-86e1b7b0578d)

im config der weboberfläche

**Comment by csh-de** [comment]
ich hätte ja gerne Standby an von 8-14uhr und den Rest ohne Standby, weil mit ist die Erreichbarkeit bei mir eingeschränkt... aber dennoch funktioniert es und das ist mir wichtiger als das die Verbrauchs-Zähler nicht gespeichert würden...

**Comment by steff393** [comment]
Hi, mit der aktuellen SW x.5.2 ist der Parameter cfgStandby nicht mehr relevant. Stattdessen geht http://wbec.local/json?standby=0 (aktiv) oder = 4 (inaktiv). Meine Empfehlung bleibt weiterhin der Wert 4.
Der Energiezähler ist lt. Heidelberg-Anleitung nicht für Abrechnungszwecke geeignet. 
Wenn die Box im Standby ist, ist keine Kommunikation möglich, also auch keine Änderung desselben. Da das Thema schon komplex genug ist (z.B. für Lastmanagement und EnWG) wird auch keine zeitliche Abhängigkeit umgesetzt, sondern man muss sich für das eine odere andere entscheiden und mit den Konsequenzen leben.
