### ISSUE TITLE
Energywert (Energy Total, energyI) nach Stromausfall auf 264,9kWh zurückgesetzt

### ISSUE THREAD

**Issue by hdlange** [steff393/wbec#132]
Hallo,
ich habe den komischen Effekt, dass in 2 Fällen (in den letzten 5 Tagen) durch jeweils einen Stromausfall der Wert energyI auf den Wert 264,9 zurückgesetzt wurde. Vor dem ersten Stromausfall war der Wert bereits 532kWh, vor dem zweiten bei 284,26kWh.
Ist das ein Bug, oder hat meine Wallbox da ein Problem und meldet genau diesen Wert nach einem Stromausfall?
Wallbox und wbec waren jeweils durch den Stromausfall betroffen.
wbec Version 1.5.1
Wallbox 00.779.9065 001742 2212 HD_EnergyControl

**Comment by steff393** [comment]
Hallo,
ja, das ist leider eine Eigenschaft der Wallbox. Diese speichert den Energiezähler nur ab, wenn sie in den Standby geht. 
Die Nutzung des Standby hat aber zur Folge, dass die Wallbox immer beim Aufwachen den Strom erstmal auf 0 setzt. Ich denke daher, dass der deaktivierte Standby immer noch die bessere Variante ist, auch wenn dadurch der Zählerwert verloren gehen kann.
