### ISSUE TITLE
Not able to get value for "Bezug(+)/ Einsp.(-")

### ISSUE THREAD

**Issue by Timmy2807** [steff393/wbec#135]
Ich habe meine Energy Control von Heidelberg erfolgreich verbindne können und kann auch über die wbec.local Seite die Steuerung grundsätzlich vornehmen, allerdings bekomme ich den Wert "Bezug(+)/ Einsp.(-") nicht (mehr angezeigt). Ich vermute eine fehlerhafte Einstellung in der Config, finde allerdings meinen Fehler nicht. Die Einbindung in OpenWB hatte ich schon versucht, wollte aber zuerst das Grundsätzliche aufsetzen, bevor ich mich an weitere Einbindungen versuche..

So sieht meine cfg.json aus: `{"cfgApPass":"wbec1234","cfgCntWb":1,"cfgMqttIp":"\"\"","cfgMqttWattTopic":"","cfgPvActive":1,"cfgPvHttpPath":"","cfgInverterIp":"192.168.178.xxx","cfgInverterType":4,"cfgInverterPort":502,"cfgChargeLog":1}`

und unter wbec.local/json bekomme ich folgendes zurück: 
`{"wbec":{"version":"v1.5.2","bldDate":"Apr  6 2024 10:58:39","timeNow":"22:13:32","enwg14a":0,"enwgErr":0},"box":[{"busId":1,"version":"108","chgStat":4,"currL1":0,"currL2":0,"currL3":0,"pcbTemp":295,"voltL1":245,"voltL2":241,"voltL3":244,"extLock":1,"power":0,"energyP":4.087,"energyI":105.024,"energyC":0,"currMax":16,"currMin":6,"logStr":"00.779.2909/02 033887 2210 HD_EnergyControl","wdTmOut":60000,"standby":0,"remLock":1,"currLim":0,"currFs":0,"lmReq":255,"lmLim":0,"resCode":"0","failCnt":0}],"modbus":{"state":{"lastTm":129862,"millis":134104}},"rfid":{"enabled":false,"release":false,"lastId":""},"pv":{"mode":2,"watt":0},"wifi":{"mac":"64:B7:08:B7:A7:38","rssi":-74,"signal":52,"channel":6}}`
Ich nutze eine Heidelberg Energy Control in Verbindung mit einem Huawei Wechselrichter und dem SDongle.

**Comment by abuesen** [comment]
Wie erfährt der wbec denn den Wert für Einspeisung / Bezug in Deiner Umgebung? Hat es schon mal funktioniert? 

In der config sieht man, dass mqtt gar nicht konfiguriert wurde. (Damit könnte es sich die Werte mittels `cfgMqttWattTopic` holen.) Alternativ ruft ein externes Programm das passende Kommando am wbec auf, siehe Doku. 

Falls du openWB bereits hast versuche die Anbindung darüber. Das geht auch über mqtt. 
Huawei und SDongel kenne ich nicht.

**Comment by Timmy2807** [comment]
Danke @abuesen für deine Rückmeldung! 

Tatsächlich hatte ich es schon einmal sporadisch zum Laufen bekommen. Aber seit ich OpenWB per MQTT anbinden wollte, funktioniert es nicht mehr. Hatte dann versucht, alles wieder auf die damaligen Einstellungen zu bekommen, aber seitdem bekomme ich den Wert gar nixht mehr angezeigt. In der Zwischenzeit konnte ich OpenWB über MQTT grundsätzlich einbinden und mache mich mal an deinen vorgeschlagenen Weg über `cfgMqttWattTopic `.

Danke für deine Hilfe!

**Comment by steff393** [comment]
Hi,
ich bin mir nicht ganz sicher, woran es liegt, aber man sollte die Übermittlung von Bezug/Einspeisung auf einen Weg festlegen:
- MQTT (z.B. auch openWB): cfgMqttIp und cfgMqttLp sind nötig
- HTTP-Aufrufe (z.B. Shelly): cfgPvHttpIp, cfgPvHttpPath und ggf. cfgPvHttpJson sind nötig
- Modbus-TCP (z.B. Huawei): cfgInverterIp und cfgInverterType sind nötig

Oben sind Ansätze aller 3 Methoden in der cfg.json, evtl. hat das was vermischt.
Aber es scheint sich ja mittlerweile gelöst zu haben. Sorry für die späte Rückmeldung
