### ISSUE TITLE
Anbindung Sungrow Inverter ModBus TP

### ISSUE THREAD

**Issue by N4zroth** [steff393/wbec#137]
Hi,
ich würde gerne einen PR stellen in dem die Anbindung an einen Sungrow SH10RT-V112 ermöglicht wird. Ich lese sowieso schon diverse Daten des Inverters aus um Grafana/Influx zu befüllen. Leider verstehe ich die Variablen in inverter.cpp eher weniger und der Inverter unterstützt leider kein Sunspec.
Außer dass pwrMet irgendwie das Ergebnis der Berechnung ist, blicke ich nicht wirklich durch. Gibt's da irgendwo eine Doku oder einen Hinweis zu? Danke!

**Comment by steff393** [comment]
Hi,
die Unterstützung für Sungrow Wechselrichter ist bereits für die Pro-Varianten eingebaut:
https://steff393.github.io/wbec-site/

Das kommt im nächsten Release (1.5.3 bzw. 2.5.3), allerdings auf die wbecPro, wbecLan und wbecPremium. Eine Testversion kann ich vorab gern zur Verfügung stellen.

**Comment by N4zroth** [comment]
Hi,
oh super, hab's gerade auch eingebaut. Danke für die schnelle Info, dann bestelle ich demnächst eine Pro oder Premium :)

**Comment by HowardH7** [comment]
Hallo,
ist eine Einbindung von Sungrow in den "normalen" wbec auch geplant?

**Comment by steff393** [comment]
Leider nein, da unterscheidet sich aktuell der Code ziemlich stark. Sungrow nutzt anders als die anderen sog. Input-Register.

**Comment by HowardH7** [comment]
> Leider nein, da unterscheidet sich aktuell der Code ziemlich stark. Sungrow nutzt anders als die anderen sog. Input-Register.

Danke für die schnelle Antwort.
