### ISSUE TITLE
Parameter pvBatt Webserver

### ISSUE THREAD

**Issue by blob810** [steff393/wbec#138]
Im Wiki ist davon die Rede dass zusätzlich die Batterie Entlade- und Ladeleistung des PV-Speichers übertragen werden kann. 

siehe https://github.com/steff393/wbec/wiki/Configuration-Example%3A-Home-Assistant

gibt es diesen Wert noch, denn ich kann weder in PVAlgo.cpp noch unter Webserver.cpp etwas davon finden.

**Comment by steff393** [comment]
Hi,
der Wert ist aktuell nur in den Fertigmodulen verfügbar, ab Version 1.4.8 und größer
https://github.com/steff393/wbec/releases/tag/v0.4.8
