### ISSUE TITLE
WBEC does not connect back to Wifi Network after power outage

### ISSUE THREAD

**Issue by Chaosflori25** [steff393/wbec#139]
My Wifi Network takes a bit, but it happend a few times in the last year, and I'm tired of running arround replugging the ESP after the Outage. Any Ideas how I could fix that?

Best Regards

**Comment by steff393** [comment]
Hi,
there is the following parameter:
uint16_t cfgWifiConnectTimeout;       // Timeout in seconds to connect to Wifi before change to AP-Mode

Default is 10s

**Comment by andreas5232** [comment]
I've just stumbled upon the same issue. After power outage my wifi access point in the garden needs more than 10s to initialize and wbec is "stuck" in AP mode. Took me some time to figure it out... 

Maybe a more conservative default value of 120s is a better default value for cfgWifiConnectTimeout?
