### ISSUE TITLE
Problems using ioBroker/go-e adapter

### ISSUE THREAD

**Issue by moddmylife** [steff393/wbec#14]
hello anyone, 
i tried using the Go-E-Charger adapter to include the WBEC into my HA-System. But everytime i got an API-Error
![grafik](https://user-images.githubusercontent.com/59995161/145715075-dcd95f84-a876-4b8e-83e2-a2913ba249a8.png)

any ideas to solve this?

**Comment by steff393** [comment]
Hi 
sorry, wbec emulates only a part of the go-E API (i.e. the main variables needed by Wallbox Steuerung App, openWB and EVCC). 
The API seems to increase and increase every few weeks, so it's not possible to remain always up to date. And it doesn't make sense to send dozens of values just with constant default values (from my point of view).

So I'd suggest to solve this on the ioBroker side. Maybe the checks of the unneeded variables can be disabled?

**Comment by moddmylife** [comment]
> Hi sorry, wbec emulates only a part of the go-E API (i.e. the main variables needed by Wallbox Steuerung App, openWB and EVCC). The API seems to increase and increase every few weeks, so it's not possible to remain always up to date. And it doesn't make sense to send dozens of values just with constant default values (from my point of view).
> 
> So I'd suggest to solve this on the ioBroker side. Maybe the checks of the unneeded variables can be disabled?

No problem. i'll do a little bit of json-magic and see what happen. 
but thank you for your quick reply!

**Comment by maxpd1** [comment]
Is there an official manual how to do the json magic?
