### ISSUE TITLE
Bug in feature: Load log: Instead of 20, up to 50 entries can now be read if required (log.js, line 46 -> len=50)

### ISSUE THREAD

**Issue by sam-harder** [steff393/wbec#140]
If the log list has been expanded to 50 entries, new loads will not be displayed. When the list is restricted to 20 lines again, the most recent loads appear on top.

**Comment by steff393** [comment]
Hi, 
can you please send me your chargelog-0.txt file via wbec393@gmail.com?
Then I'll try to reproduce.

**Comment by sam-harder** [comment]
Hallo,Sorry, beim Versuch diese Datei herunterzuladen habe ich sie scheinbar zerschossen. Zeigt nun völligen Unsinn an. Wie bekomme ich diese Datei gefahrlos heruntergeladen?Kann ich diese Datei einfach löschen?Viele Grüße Hans-Joachim HarderAm 24.06.2024 um 21:23 schrieb steff393 ***@***.***>:﻿
Hi,
can you please send me your chargelog-0.txt file via ***@***.***?
Then I'll try to reproduce.

**Comment by steff393** [comment]
Hi, das ist ganz normal, dass die Datei sehr seltsam aussieht, wenn man sie im Editor oder unter wbec.local/edit anschaut.
Kein Problem.

**Comment by steff393** [comment]
Rechtsklick --> Download

**Comment by sam-harder** [comment]
Hallo,bin auf dem IPad unterwegs und finde leider keine Option den Download zu starten.Aber bei meinen unbedarften Versuchen das hinzubekommen, habe ich wohl den Inhalt der Datei verändert, denn wenn ich das Log aufrufe, sind darin unsinnige Werte zu sehen. (Hänge ein Bild an)Gruß Sam Am 24.06.2024 um 22:02 schrieb steff393 ***@***.***>:﻿
Hi, das ist ganz normal, dass die Datei sehr seltsam aussieht, wenn man sie im Editor oder unter wbec.local/edit anschaut.
Kein Problem.
