### ISSUE TITLE
Iphone Browser Kompatibilität 

### ISSUE THREAD

**Issue by BjoernH1896** [steff393/wbec#147]
Hi, keine Ahnung ob es nur mir so geht, aber ich habe eigentlich immer Probleme beim aufrufen der Startseite des wbec mit dem iPhone. Vom Mac aus ist es gar kein Problem, aber vom iPhone wird die Seite nur unvollständig geladen und man kann es nicht wirklich benutzen. Die andren Reiter Zeit, Config usw. gehen Problemlos. Hat jemand einen Tip für mich? Oder vielleicht eine alternativ Browser Empfehlung mit der das Phänomen nicht auftritt?

Gruß, Björn

**Comment by steff393** [comment]
Hallo,
bei mir läuft es auch mit dem IPhone einwandfrei.
Eventuell helfen bei dir folgende Maßnahmen:
Issue https://github.com/steff393/wbec/issues/123
Issue https://github.com/steff393/wbec/issues/99
