### ISSUE TITLE
FRAGE: ist die Heidelberg noch state of the art für Überschussladen ? 

### ISSUE THREAD

**Issue by typxxi** [steff393/wbec#150]
Wir haben eine 11 kW Wallbox von Wallbox und überlegen eine andere zu kaufen, um Dinge wie OCPP laden stabiler hinzubekommen.

Wie zufrieden sind die Besitzer und klappt diese auch hier diskutierte (dynamische) Umschaltung von 3 auf 1 Phase (durch Kappen von 2 bzw. 1 Phase) und umgekehrt ?

Wallbox ist sau langsam bei der Firmware, hat wohl x verschiedene Hardwarestande ihrer Wallboxen über Jahre verkauft, aber immer gleich genannt, was nun bei der Firmware auf einmal auffliegt, weil die OCPP Integration von denen fehlerhaft ist und nur bei der neuesten Hardwareversion bzw. den in 2024 verkauften Wallboxen gefixt ist, da alle anderen auf Firmware 5.x hängen und nicht auf 6.x kommen. 

Daher die Frage zur Zufriedenheit auch mit dem Phasenwechsel, der bei uns wichtig ist in der Übergangszeit, auch wenn wir 25 kWp haben.
Wir nutzen evcc mit der Pulsar Plus von Wallbox.

Danke

**Comment by abuesen** [comment]
Hi @typxxi

Deine Frage lässt sich insgesamt nur mit _nein_ beantworten, was an Deinen Anforderungen liegt.

Die Heidelberg kann keine Phasenumschaltung. Die wurde extern selbst dazu gebaut.

Über wbec kann sie kein ocpp. Es gibt nur den Modbus als Schnittstelle an der Hardware.

Trotzdem halte ich die Heidelberg EC noch für state of the art und absolut für Überschussladen geeignet. 

Die Steuerung über Modbus ist für HEMS Standard und ich konnte die HD EC nahezu Plug and Play einbinden. Mit oder ohne wbec.

Das Überschussladen funktioniert mit drei Phasen einwandfrei. Mein Auto kann keine dynamische Umschaltung der Phasen, vom Hersteller nicht erlaubt und es klappt auch nicht. 
Vermisst hab ich das auch nicht, da der Ertrag für eine Phase in den schwachen Monaten eh nicht reichen würde. Ich lade bereits bei 2kW Überschuss und nehme den Rest aus dem Netz. Die komplexe Regelung übernimmt mein HEMS. Wbec ist Konverter und Fallback für HEMS Fehler, wäre nicht notwendig.

Die HD EC ist ausgereift und läuft absolut stabil. Wegen der nicht vorhandenen web-Schnittstelle sind Sicherheits- und Feature-Updates kaum erforderlich.

Aber wie gesagt, deine Anforderungen erfüllt sie nicht. Für dich ist sicherlich eine Box mit eingebauter TCP/IP Schnittstelle und API die geeignetere Lösung.

LG.
