### ISSUE TITLE
Zeitsteuerung nicht möglich, lädt direkt

### ISSUE THREAD

**Issue by VedMod** [steff393/wbec#152]
Ich wollte die Tage von 00:00Uhr bis 05:00Uhr laden um den Preis von 0,20€/kWh via Tibber auszunutzen.
Habe auf der "Zeit" Seite entsprechend die Regler gestellt.

Beginn: 00:00Uhr, 16A
End: 05:00Uhr, 16A,
Zeit nur einmalig (checked)
Nur Aus Schalten (unchecked)
Energielimit: + 100kWh
Energielimit bei jeder An-Phase neustarten (checked)

Speichern gedrückt
-> Wechsel auf die Übersicht, ~20sek später Auto lädt mit 11kW :/

Hatte dann im Code gesehen das bei aktiviertem PV Laden der Algo anders läuft
https://github.com/steff393/wbec/blob/cd5e943093a7093589d97a786260048fe79659e4/src/pvAlgo.cpp#L128C6-L128C13
Hatte dann PV Laden deaktiviert und wbec reseted, das hat aber kein Unterschied gemacht. Zudem wiederspricht es ja der Beschreibung der Zeitfunktion "_Mittels "nur Aus-Schalten" lässt sich dies jedoch auf die Aus-Phase begrenzen. Somit kann man in der An-Phase den Strom durch z.B. PV-Überschussladen dynamisch regeln lassen_"

Im Einsatz habe ich wbecLan (2.5.3). 

P.s.: Die Beschriftung der Buttons ist sehr verwirrend, 
Laden bedeutet das Auto laden? Die einstellungen so "übernehmen" und entsprchend laden? Muss ich erst Speichern drücken dann laden?

Außerdem fehlt auf der Homeseite eine Anzeige welche Regelung gerade aktiv ist.

**Comment by steff393** [comment]
Hi, 
wenn du sowohl in der AN-Phase, wie auch in der AUS-Phase mit 16A laden möchtest, dann lädt die Wallbox immer mit 11kW :-)

Laden: Lädt die aktuellen Werte aus wbec in die Weboberfläche
Speichern: Speichert die Werte der Weboberfläche ins wbec
Deaktiviereren: Deaktiviert die Zeitsteuerung komplett

**Comment by VedMod** [comment]
> Hi, wenn du sowohl in der AN-Phase, wie auch in der AUS-Phase mit 16A laden möchtest, dann lädt die Wallbox immer mit 11kW :-)

Ja das war auch der Plan ;) 
Okay hätte noch ein paar mehr Details geben können.

Also es ist 18/19Uhr, ich gucke auf die Strompreise meines Dynamischen Stromtarif und sehe das in der Nacht von 00:00 - 05:00 Uhr der Strompreis unter 0,20€/kWh liegt. Da aufgrund der Winterzeit das reine PV Laden eher schwer möglich ist und der Akku des Autos fast leer ist, möchte ich über Nacht laden und habe entsprechend wbec konfiguriert.

Jetzt kommt das problem, das Auto lädt direkt mit 11kW zur Uhrzeit des Einstellens und nicht erst um 00:00Uhr.

**Comment by abuesen** [comment]
> > Hi, wenn du sowohl in der AN-Phase, wie auch in der AUS-Phase mit 16A laden möchtest, dann lädt die Wallbox immer mit 11kW :-)
> 
> Ja das war auch der Plan ;) 

Der Plan ist nicht eingestellt.

> Beginn: 00:00Uhr, 16A 
> End: 05:00Uhr, 16A

Beginn: 00:00Uhr, 16A 
End: 05:00Uhr, **0**A

So habe ich Steff jedenfalls verstanden =)

LG.

**Comment by VedMod** [comment]
> Der Plan ist nicht eingestellt.
> 
> > Beginn: 00:00Uhr, 16A
> > End: 05:00Uhr, 16A
> 
> Beginn: 00:00Uhr, 16A End: 05:00Uhr, **0**A
> 

aaaaaahhhh! 
Ich hatte es so verstanden das die Einstellung für Ende sagt: "bis 05:00 lade mit 16A".
Hatte mich dann wohl von der Anzeige der "Geschätzen Ladung" in die irre führen lassen. Da stand halt genau die Werte die ich erwartet habe, 5 Std x 11kW = ~55kWh geladen.

@steff393  ist das genauso gemeint ja?

**Comment by steff393** [comment]
Ja, stimmt genau.
Vielleicht sollte es genauer "Geschätzte Ladung während der AN-Phase" heißen...

**Comment by VedMod** [comment]
> Ja, stimmt genau. Vielleicht sollte es genauer "Geschätzte Ladung während der AN-Phase" heißen...

Ich meinte, dass ich mich durch die Anzeige der Schätzung in die Irre führen lasse habe, das es so richtig eingestellt ist. So hab ich gedacht es ein Bug ist und nicht das an mein Einstellungen was falsch und hätte vielleicht noch mal drüber nachgedacht ;)

**Comment by VedMod** [comment]
Kurzes Update, läuft alles wie es soll 💯 
![grafik](https://github.com/user-attachments/assets/bfeb19ce-1b55-4464-a060-32291e9fedae)

![grafik](https://github.com/user-attachments/assets/1813d0ec-9dec-49df-a7da-c9e7abc6657c)

Nur das Auto wollte nicht mehr um kurz vor 6Uhr, es hatte bereits die 100% erreicht 👍🏻
