### ISSUE TITLE
Port ändern MQTT

### ISSUE THREAD

**Issue by anselra** [steff393/wbec#16]
Hallo zusammen,
erstmal ein Gutes Neues und Glückwunsch zu diesem tollen Projekt.
Ich binde WBEC mit Hilfe von MQTT an meinen IOBroker an. Leider habe ich keine Möglichkeit gefunden den Port anzupassen. Dies ist bei mir aber leider notwendig. Kann mir da jemand weiterhelfen, vielen Dank

**Comment by steff393** [comment]
Hallo anselra,
dankeschön, wünsch ich dir ebenso. Du meinst hier statt 1883 einen parametrierbaren Wert, oder?
client.setServer(cfgMqttIp, 1883);

Ja, das könnte ich zur nächsten Version umsetzen.

**Comment by anselra** [comment]
Ja genau, ein parametrierbarer Wert wäre am besten.
"cfgMqttIp":"192.168.178.1:xxxx"

klasse Vielen dank

**Comment by steff393** [comment]
Wird in der nächsten Version drin sein als neuer Parameter, den man z.B. so setzen kann: "cfgMqttPort":42
Default ist 1883.
Den Code habe ich vorher schon hochgeladen.

**Comment by anselra** [comment]
super, danke
