### ISSUE TITLE
Error: Comm-Failure BusID 1

### ISSUE THREAD

**Issue by oldgitdaddy** [steff393/wbec#20]
Hallo zusammen,
Seit geraumer Zeit habe ich das Problem, dass nach einer gewissen Zeit in der das Auto laenger an der Wallbox hängt, die Wallbox in komischen Zustand fällt. Ich habe das Problem bereits bei EVCC adressiert, gleichzeitig möchte ich Fehler bei wbec ausschliessen.

Aktuelle Diskussion: https://github.com/evcc-io/evcc/discussions/2607

Für debugging habe ich nun das MQTT log aktiviert. Bekomme nun also für meine eine Wallbox unterschiedliche Nachrichten. Unter anderem folgende: 
`MB : Comm-Failure BusID 1`
Es scheinen also mindestens Events gelogged zu werden, die nicht erfolgreich sind. 

Gibt es schon jemanden, der ähnliche Fehler oder Probleme mit der EVCC/wbec Installation hatte? Freue mich auf feedback!

**Comment by steff393** [comment]
Hi,
die Meldung "Comm-Failure BusID 1" kommt, wenn eine Botschaft auf dem Modbus nicht beantwortet wurde. Das kommt hin- und wieder vor (auch bei mir alle paar Minuten), ist aber kein Problem, eher ein Hinweis.

Alle Werte werden alle 10s (cfgMbCycleTime) neu übertragen. Wenn mal einer "verloren" geht, dann bleibt der alte Wert stehen und 10s später kommt der nächste Versuch, der dann ja in der Regel erfolgreich ist.
Wenn mehrere Botschaften direkt nacheinander nicht beantwortet werden, dann ist erfahrungsgemäß irgendwas mit dem Kabel/Abschlusswiderstand (oder vielleicht eine starke Störquelle in der Nähe).
Bei 15 fehlerhaften Botschaften nacheinander erkennt wbec einen Verbindungsabbruch.
