### ISSUE TITLE
Ethernet Anbindung Wbec

### ISSUE THREAD

**Issue by taschaue** [steff393/wbec#21]
Guten Tag, 
hat jemand eine Anbindung per Ethernet statt Wifi realisiert? Wird das unterstützt?

Danke
taschaue

**Comment by steff393** [comment]
Hallo taschaue,
mit dem verwendeten Mikrocontroller geht es meines Wissens nicht. 
Mögliche Alternative, wenn schon ein Netzwerkkabel bei der Wallbox liegt: Das Netzwerkkabel für den Modbus nutzen und wbec am anderen Ende (ist ja in der Regel neben dem WLAN-Router) platzieren.
Ist dann fast wie mit Ethernet und hat den Vorteil, dass die Router (z.B. Fritzbox) oft auch gleich einen USB-Anschluss zur Stromversorgung haben, d.h. man spart sich das USB-Netzteil.

**Comment by taschaue** [comment]
Danke für die Info.
Gab es mal einen Test mit einem ESP32? Weil da gibt es z.B. von Olimex den ESP32-PoE?

**Comment by steff393** [comment]
Bisher noch nicht. Soweit ich weiß, müsste man für den Umstieg vom ESP8266 auf den ESP32 einiges an den Libraries ändern/austauschen (z.B. SPIFFS/LitteFS, etc.). Hab ich bisher nicht in Angriff genommmen.

**Comment by taschaue** [comment]
Danke für die Info. Ist übrigens ein echt tolles Projekt!
