### ISSUE TITLE
Steuerung von 2 Wallboxen über Webinterface nicht (mehr) möglich

### ISSUE THREAD

**Issue by Clanchef** [steff393/wbec#23]
Hallo Stefan,
ich habe ja inzwischen 2 Heidelberg Wallbox an einer wbec dran hängen. Seit dem letzten Update kann ich im Web Interface nicht mehr zwischen den beiden Boxen auswählen, es wird immer nur die erste angezeigt.
Liegt das an dem neu eingeführten Exit Knopf?

```
<div>
	<right>
		<button id='btnExit' style="font-size: 6pt; float: right;">X</button><br>
	</right>
</div>
<h1>wbec</h1>
<div id='boxSelection'>
	<button id='btn1' class="button">BMW</button>
	<button id='btn2' class="button">Mini</button>
	<button id='btn3' class="button">None</button>
</div>
<br>
```

**Comment by steff393** [comment]
Hi,
hab's grad bei mir ausprobiert, da funktioniert die Umschaltung richtig. Hast du in **beiden** Dateien (web.html und web.js) die Kommentarzeichen für die Buttons rausgelöscht?
- HTML: `<!-- und -->`
- JS: `/* und */`

https://github.com/steff393/wbec/blob/1d7db976688a5f9d187777a3d62c13221ff012a1/data/web.html#L20-L27

https://github.com/steff393/wbec/blob/1d7db976688a5f9d187777a3d62c13221ff012a1/data/web.js#L91-L101

**Comment by Clanchef** [comment]
Hallo Stefan,

vielen Dank für die schnelle Hilfe. Ja das wars, habe beim web.js die Kommentarzeichnen nicht rausgenommen. Das war schon länger bei mir her als wir das mit den 2 Boxen gemacht haben. Werde mir auch das mit dem Solaredge WR mal ansehen.

Grüße
Martin

**Comment by steff393** [comment]
Kein Problem, dann ist es jetzt mal dokumentiert ;-)
