### ISSUE TITLE
Wattangabe nicht stimmig?

### ISSUE THREAD

**Issue by frad1980** [steff393/wbec#26]
Hallo, wenn ich die Wattwerte von meinem Smart Energy meter kontrollieren, dann sehe ich eine Diskrepanz. In wbec bekomme ich mehr Watt (Leistung) angezeigt, als mein Energymeter aktuell verbraucht...?

![image](https://user-images.githubusercontent.com/102154150/159470503-e5c0c6bf-17f5-476b-9469-e719900b3de4.png)

Muss da noch etwas angepasst werden an der Config?

**Comment by steff393** [comment]
Gute Frage!
Das W in wbec ist eigentlich nicht richtig. Der interne Werte in der Heidelberg wird in VA angeben. Diesen übernehme ich 1:1.
Könnte ein Effekt von Wirkleistung & Blindleistung sein. Aber da kenne ich mich zu wenig aus und ich hätte vermutet, dass die Abweichung deutlich geringer sein müsste.
Grundsätzlich wären 5,5kW bei 8A schon plausibel (entspricht 11kW/16A), wenn das Auto den max. Strom zieht.

**Comment by DrGalvany** [comment]
Hallo,
bei meinem Fahrzeug stimmt die Anzeige von wbec.
Meines lädt aber nur einphasig.
Welches Fahrzeug hast du daran?
Lädt es ein, zwei oder dreiphasig?
Schaue auch mal direkt im KSEM nach, da die Anzeige des Penticors evtl. hier abweicht.

**Comment by steff393** [comment]
Scheint sich erübrigt zu haben
