### ISSUE TITLE
Zoe laden mit 6A nicht möglich

### ISSUE THREAD

**Issue by frad1980** [steff393/wbec#28]
Hallo, hat jemand auch das "Problem", dass die Renault Zoe bei 6A nicht lädt? Erst ab 8A kann ich laden.

Ist es möglich per Befehl auch auf 7A zu schalten?
http://192.168.xx.yy/json?currLim=70

**Comment by steff393** [comment]
Hallo, soweit ich weiß ist diese Einschränkung Zoe-seitig. Der Lader funktioniert nur mit >8A, d.h. auch der Drehschalter innen in der Wallbox (für Minimalstrom) sollte schon auf 8A gestellt sein.
