### ISSUE TITLE
Absicherung von Schreibvorgängen per HTTP Basic Auth oder mit einem Token

### ISSUE THREAD

**Issue by abias** [steff393/wbec#31]
Mit WBEC kann ich ja nicht nur die über MODBUS veröffentlichten Werte aus der Wallbox auslesen, sondern auch die Ladestromeinstellungen schreiben und damit auf den Ladevorgang Einfluss nehmen. Dies ist mit einem simplen HTTP Aufruf möglich.

Dieser HTTP Aufruf ist nicht authentifiziert, das heißt jeder Rechner im selben Netzwerk kann ihn ausführen, was über die Zeit zu einem Sicherheitsrisiko führen könnte falls man nicht strikte netzwerktechnische Trennungen vornimmt.

Ich würde gerne vorgeschlagen alle schreibenden Aufrufe per HTTP Basic Auth oder einem Token (als URL Parameter) abzusichern. Da die Verbindung unverschlüsselt ist (und HTTPS für die verwendete Platine eine große Herausforderung wäre) wäre dies keine absolute Sicherheit und ein Angreifer im selben Netz könnte die Zugangsdaten immer noch mitlauschen. Aber es würde die Latte ein ganzes Stück höher legen.

Vielen Dank!

**Comment by steff393** [comment]
Ich halte nichts davon, einen Weg abzusichern, wenn zig andere (Websocket, MQTT, OTA Update, usw.) offen sind. 
Und nebenbei ärgere ich mich grad über diesen ganzen IT-Sicherheits-xxxxxx, weil mir Google heute mitgeteilt hat, dass sie mich ab 30. Mai zu OAuth 2.0 zwingen :-(
Sorry, schlechtes Timing... ;-)
