### ISSUE TITLE
Einstellung für minimalen Intervall zwischen Ladestromänderungen

### ISSUE THREAD

**Issue by abias** [steff393/wbec#32]
Mit WBEC kann ich ja nicht nur die über MODBUS veröffentlichten Werte aus der Wallbox auslesen, sondern auch die Ladestromeinstellungen schreiben und damit auf den Ladevorgang Einfluss nehmen. Dies ist mit einem simplen HTTP Aufruf möglich.

Ich kann mir vorstellen dass es nicht ganz gesund für die Wallbox und / oder das Auto wäre wenn ein amoklaufendes Smart Home Script oder auch ein Angreifer im selben Netzwerk die Ladestromeinstellungen in sehr kurzen Abständen zigfach hoch- und runterstellt.

Gibt es eine Möglichkeit (über eine Konfigurationsdatei) einen minimalen Intervall zwischen zwei Ladestromänderungen festzulegen oder, falls nicht, könnte diese Möglichkeit implementiert werden?

Vielen Dank!

**Comment by steff393** [comment]
Der Parameter cfgMbDelay könnte dafür verwendet werden, bremst dann bei großen Werten aber auch generell die Kommunikation aus.
Meines Wissens gibt es keine definierte Zeit, ab der man sicher sagen könnte, dass der Abstand ausreichend groß ist. Man kann (theoretisch) mit 100ms genauso Pech haben wie mit 100s, wenn es keine spezifizierte Zeit gibt. Aber ich sehe auch keine fundierte technische Begründung (konkret für die Heidelberg), warum kurze Intervalle problematisch sein könnten.
