### ISSUE TITLE
WLAN Verbindung mit fester IP Adresse / ohne DHCP

### ISSUE THREAD

**Issue by abias** [steff393/wbec#33]
Im Access Point Mode kann ich WBEC mit meinem WLAN verbinden und gebe dazu die SSID und das Passwort ein. WBEC scheint dabei aber nur mit DHCP zu arbeiten und darauf angewiesen zu sein dass ein DHCP Server im WLAN läuft. Für Installationen bei denen IoT Geräte absichtlich ein eigenes WLAN haben und feste IPs bekommen ist das eher ungeschickt.

Gibt es eine Möglichkeit (über eine Konfigurationsdatei) eine feste IP Adresse für die WLAN Verbindung zu konfigurieren oder, falls nicht, könnte diese Möglichkeit im Access Point Mode implementiert werden?

Vielen Dank!

**Comment by steff393** [comment]
Sollte machbar sein, aber ich muss mir erst anschauen wie es geht.

**Comment by steff393** [comment]
Ich habe hier gefunden wie man es umsetzen könnte:
https://www.xgadget.de/anleitung/esp8266-feste-ip-adresse-vergeben/

Allerdings passt das dann nicht mehr zu dem WiFiManager code. Daher würde ich es nicht in den allgemeinen Code übernehmen. 

Aber wer möchte, kann es natürlich bei sich lokal ändern: Man müsste also den WifiManager entfernen und stattdessen die Zugangsdaten und die statische IP wie in dem Beispiel direkt im Code eingeben.

Das ganze wäre ungefähr hier zu ändern:
https://github.com/steff393/wbec/blob/a90fed762dad8706cbd540d254af02859c6ed74c/src/main.cpp#L39-L42
