### ISSUE TITLE
Ethernet Version

### ISSUE THREAD

**Issue by moddmylife** [steff393/wbec#34]
Good morning.
First, thank you for brilliant work!
I have some issues with my wireless network. If it fails, wbec stopped working and the Heidelberg energy control goes into bus error. 
Nothing that depends on wbec, only on my wireless network and my house made of steel (I think)...

Is it possible to include Ethernet modules like the W5500 or ENC28J60 to control everything over wired network? Maybe PoE is also possible.

**Comment by steff393** [comment]
Hi,
that's a typical question. Many people choose the following alternative:
![grafik](https://user-images.githubusercontent.com/73853447/167246116-8eba3ae0-3f03-402c-b7ca-a40c3ba517f7.png)


Of course it's no 'real' Ethernet, but I'd say it has no significant disadvantages compared to Ethernet.

**Comment by moddmylife** [comment]
Good morning and thanks for quick response!
Thats a good point, but in my case I have Ethernet Distribution next to the UV where the Cable from the Wallbox came in. Best way to connect is in my case to put the ESP inside the Wallbox itself.

**Comment by DrGalvany** [comment]
Hello steff393,
have just seen the picture of the connection of the wallbox here, and I shocked.
Have in memory to have connected my cables on the right side.
So, immediately checked again and I was relieved.
The picture is visually the other way around, but correctly described.

Gruß
Micha

**Comment by steff393** [comment]
Yes, you're right IN and OUT are mirrored on the picture, sorry.
But it shouldn't matter, as IN A and OUT A are directly connected with each other on the PCB (same for B) :-)
