### ISSUE TITLE
WLAN reconnect

### ISSUE THREAD

**Issue by elektronikfreak** [steff393/wbec#35]
Hallo,

wenn das WLAN mal verloren geht macht WBEC keinen reconnect und ich muss den ESP aus und wieder einschalten.
Ein WLAN reconnect wäre daher super.

Vielen Dank und Grüße

**Comment by steff393** [comment]
Evtl. helfen die Vorschläge aus #12?

**Comment by elektronikfreak** [comment]
Super, das hat geholfen.

Danke
