### ISSUE TITLE
TFT Display direkt an wbec

### ISSUE THREAD

**Issue by tobelix87** [steff393/wbec#37]
Hallo zusammen,

die Heidelberg Control wird demnächst montiert und ich plane wbec mit einem kleinen TFT Touchscreen zu verwenden und direkt neben die Wallbox zu hängen. Auf dem Display will ich dann 2-3 Werte anzeigen lassen und mit zwei Buttons den Ladestrom ändern.

Ich bin neu in der C++ Programmierung und da die Wallbox noch nicht in Betrieb ist, kann ich auch noch nicht richtig testen, daher hab ich ein paar Fragen.
Ich habe wbec auf einen Wemos D1 mini geflashed und konnte über den Webserver darauf zugreifen. Funktioniert soweit. Als nächstes habe ich das Display angeschlossen und angesteuert. Funktioniert auch.

Nun zu den Fragen:

1. Sehe ich das richtig, dass ich die Stromstärke über den Aufruf von _lm_storeRequest(id, val)_ setzen sollte? Wobei id die ID der Wallbox im Modbus ist und val einen Wert zwischen 60 (=6A) und 160 (=16A) haben muss?
2. Wenn ich Werte aus der Wallbox auslesen will, z.B. aktuelle Ladeleistung dann include ich einfach _<mbComm.h>_ und kann dann über _content[id][10]_ den Wert abrufen?

Vielen Dank im Voraus!

**Comment by ChristianNebendahl** [comment]
Hi,
ich habe mir einen 2.ten Controller mit Display ("Zuladungs-Controller") parallel zur Heidelberg Energy Control und dem WBec gehängt, um an dem WBec Interface nichts ändern zu müssen (Ich möchte gerne kompatibel mit steff393 Lösung bleiben, um bei Updates einfach mit schwimmen zu können). Ich hatte den zusätzlichen Wunsch die Zuladung bequem einstellen zu können (Da die Batterie die teuerste Einheit in einem Elektroauto ist, betreibe ich sie möglichst nur in einem schonenden Bereich von 20-80%. Leider ermöglicht mein Hyundai keine automatische Ladezustandsabfrage, weswegen ich basteln musste). 
Im Unterschied zu Dir benutze ich OpenWB als zentrale Steuereinheit, dass den Ladestrom in Abhängigkeit der Leistungen meiner PV-Anlage regelt. Ebenso wie Du wollte ich die aktuellen Ladedaten zusätzlich angezeigt bekommen.  
Der Zuladungs-Controller hat ein kleines Display an Board ->ESP8266 mit integriertem 0,91" Oled Display, den kannst Du für wenige Euro bei AZ-Delivery bekommen. Nach Betätigen des Startknopfs am Ladecontroller wird der OpenWB Modi (PV Only, Min PV, Sofort, Stop) auf dem Display angezeigt, bevor die Anzeige auf die Zuladung, die Zielzuladung und die Ladeleistung wechselt. 

Ich hab Dir den Source Code zum "Zuladungs-Controller" anhängen. Anzupassen ist die Batteriegröße sowie die IP Adresse. 
Über ein bistabiles Relais am Zuladungs-Controller gebe ich die Wallbox frei bzw. sperre sie. Dies könntest man auch per SW machen. Ich hab es bei dem bistabilen Relais gelassen, da ich den "Zuladungs-Controller" von Vorgänger-Projekt vererbt habe, bevor ich die WBec Lösung von Steff393 gefunden habe.

Christian

![SOC](https://user-images.githubusercontent.com/8463850/172371456-fa4fcf07-8b49-4ffd-b8bf-c9b9394a3553.jpg)
[SOC_Control_ESP8266IntegriertemDisplay_Template.zip](https://github.com/steff393/wbec/files/8852848/SOC_Control_ESP8266IntegriertemDisplay_Template.zip)

**Comment by tobelix87** [comment]
Hallo Christian,
auch ein schöner Ansatz, danke fürs Teilen. Ich werde da mal rein schauen.

Ich will mir (vorerst zumindest) nicht noch ein zusätzliches Gerät da hin hängen. 
Ich habe jetzt einen ersten Test mit der Wallbox gemacht, allerdings noch ohne Auto dran. Ich konnte über den Touchscreen die Ladeleistung regeln. Akt. Ladeleistung zeigt er natürlich nix an ohne Auto.
Aber ich bin zuversichtlich dass das funktioniert. Werde ansonsten hier berichten, wenn alles final in Betrieb ist.

Ich hab an wbec bisher kaum was geändert. Nur die PIN_RST_PV_SWITCH und PIN_SS hab ich im Code auf ungültige PINs gesetzt, weil ich D3 und D8 fürs Display brauche. PV Steuerung brauche ich aktuell noch nicht und PIN_SS hab ich nicht ganz verstanden. damit kann ich wohl einen RFID Leser anschließen?
Und ansonsten meinen Code ins Loop der Main Funktion gehängt.

**Comment by tobelix87** [comment]
Sooo, ich konnte jetzt endlich mal mit Auto testen. Funktioniert soweit alles ganz gut.
![PXL_20220730_133448560](https://user-images.githubusercontent.com/105373566/182239934-7575d9ec-c368-4e41-9b18-80b429d7bf77.jpg)
Paar kleine Bugs muss ich noch beheben -z.B. sind natürlich keine 60A sondern nur 6A.

Eine Frage noch für die mir spontan keine einfache Lösung einfällt:
Wie könnte ich auf dem Display jeweils die geladene Energiemenge für den aktuellen Ladevorgang anzeigen? Aktuell zeigt es mir die Energie seit Poweron, aber das kummuliert ja immer weiter auf.
Ich will quasi die Energiemenge nach Abstecken (oder Anstecken) des Autos immer auf Null setzen.

**Comment by tobelix87** [comment]
Nochmal eine Nacht drüber geschlafen...
Ich kann einfach über den ChargeState prüfen ob ein Auto angesteckt wurde, dann den aktuellen Zählerstand abspeichern und dann von diesem gespeicherten Wert immer die Differenz zum jeweils aktuellen Wert berechnen. Sollte funktionieren. Teste ich die Tage und berichte.

**Comment by steff393** [comment]
Hi @tobelix87, 
die Version 0.4.5 wird bald verfügbar sein und dann einen Wert "energyC" enthalten, der genau diese Differenzbildung abbilden soll Hab's aber noch nicht getestet.
