### ISSUE TITLE
Kompatibilität Senec Wallbox

### ISSUE THREAD

**Issue by steff393** [steff393/wbec#43]
Hallo zusammen,

weiß jemand, ob die Senec Wallboxen baugleich zur Heidelberg sind? Ich vermute, dass wbec auch mit den Senec Wallboxen funktionieren würde.
Siehe auch hier: https://solaranzeige.de/phpBB3/viewtopic.php?t=2112

**Comment by premultiply** [comment]
Nein, tut sie nicht. Das ist keine Heidelberg EC sondern eine ABL eMH1.
