### ISSUE TITLE
Anleitung ESP + Modbus?

### ISSUE THREAD

**Issue by geek-at** [steff393/wbec#51]
Hallo, bin über Google auf dieses spannende Projekt aufmerksam geworden und habe mir jetzt die Wiki, die Webseite und den Heidelberg Blog Post durchgelesen und ich finde einfach die Anleitung für den ESP nicht.

Wie der ESP initial zu flashen und welches Modbus modul angelötet werden muss und welche Pins verwendet werden und so? Ich bin mir sicher, ich hab das nur irgendwo übersehen aber in der Wiki dazu nichts gefunden.

**Comment by steff393** [comment]
Hallo @geek-at 
wie in dem Blog-Artikel beschrieben musste ich leider feststellen, dass es sehr viel Support-Aufwand benötigt wenn Leute wbec selber basteln. Zeit, die mir für die Weiterentwicklung fehlt. Ich hab mich daher entschlossen, fertige Module mit Support zu vertreiben, s. https://steff393.github.io/wbec-site/
