### ISSUE TITLE
Fronius Inverter: Vorzeichen Smart Meter

### ISSUE THREAD

**Issue by steff393** [steff393/wbec#63]
Eine Frage an die Fronius Nutzer (z.B. @andy5macht @anselra):
Mir gefällt der folgende Code nicht mehr wirklich:
https://github.com/steff393/wbec/blob/40989cb766739b46dff8ca024af22e83f3a39b0f/src/inverter.cpp#L128-L132

Hintergrund:
Ich habe mittlerweile besser verstanden, wie der Modbus-Code darüber funktioniert:
- das mb.readHreg() stellt erstmal nur alle Abfragen zusammen
- das mb.task() schickt diese gesammelt raus und verarbeitet die Antworten auf **die Anfrage davor** (d.h. das z.B. power_meter erst einen Zyklus später als gedacht den richtigen Wert hat)

Außerdem bewirkt die Zeile
`power_meter = -1 * power_meter;`
dass eigentlich bei jedem Aufruf das Vorzeichen toggeln würde. 
Es scheint aktuell irgendwie zu funktionieren (vermutlich weil zuverlässig vorher immer ein neuer Wert ankommt), aber ich würde erwarten, dass - falls z.B. keine Antwort empfangen werden konnte - einfach mal das Vorzeichen toggelt: + - + - + 

Es gibt mittlerweile in der pv_setWatt() den Parameter cfgPvInvert mit dem man auch das Vorzeichen drehen könnte.

Ich würde daher gerne den o.g. if-Block entfernen. Könntet ihr bitte mal prüfen, ob das bei euch dann noch funktionieren würde (mit "cfgPvInvert":1)

**Comment by andy5macht** [comment]
@steff393 
Ich habe die aktuelle Version kompiliert und die Zeilen 129-132 aus der "inverter.cpp" auskommentiert.
Mit dem Parameter ""cfgPvInvert":1" passt der Wert und auch das Vorzeichen.
Kannst also aus meiner Sicht wie geplant umsetzen.
Danke - ist eine viel schönere Lösung!

**Comment by anselra** [comment]
@steff393 kann ich bestätigen was @andy5macht geschrieben hat, Danke

**Comment by steff393** [comment]
Danke euch für die schnelle Rückmeldung. Dann werd ich's demnächst mal ändern.

**Comment by steff393** [comment]
Geändert im neuen Release x.4.9
