### ISSUE TITLE
Setting up an LED charge indicator 

### ISSUE THREAD

**Issue by stephwe** [steff393/wbec#66]
The Heidelberg Energy display is difficult to see. The ESP should still have a free pin. This could be used, for example, to control an LED NeoPixel Ring WS2812 with 32 LEDs as a charge indicator. Since 5V has to be placed in the box anyway, you could use the voltage as the power supply for the LED. A simple running light during the charging process would be enough.

**Comment by steff393** [comment]
Sorry, didn't manage to integrate this for >1,5 years, so probable it will also not possible if I keep it open longer.
