### ISSUE TITLE
evcc mit nur einer Phase

### ISSUE THREAD

**Issue by emmrichd** [steff393/wbec#67]
Hallo,

ich nutze Wbec mit evcc zur Überschussladung.
Da ich nur 3.5kW Peak installiert habe, habe ich die Sicherungen der Phasen 2 und 3 raus gemacht um mit geringeren Strömen zu laden.
Muss ich nun evcc irgendwie klar machen, dass der maxcurrent geringer ist, oder generell die verfügbaren Stromstärken?

Viele Grüße, Dieter

**Comment by NongJoWo** [comment]
Moin,

wenn EVCC die Wallbox Phasen-Spannungen auslesen kann, sollte das automatisch erkannt und der Ladestrom angepasst werden.

Als E-GO-Simulation werden die Spannung durch EVCC ausgelesen, per MQTT per Standard nicht.

Wenn dauerhaft 1-Phasig geladen werden soll, am besten 1-Phasig fest unter dem Loadpoints einstellen.
[loadpoints | evcc - Sonne tanken ☀️🚘](https://docs.evcc.io/docs/reference/configuration/loadpoints/#phases)

Gruß, Jörg
