### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by hackicodi** [steff393/wbec#69]
Hallo,
ist der Betrieb auch mit einem ESP32 möglich? Beim Flashen mit dem Tool von Marcel erhalte ich keinen Zugriff auf den ESP.  WiFi ist nicht verfügbar. 

@steff393 Hatte dir auch bereits eine E-Mail bezgl Anleitung geschickt.

**Comment by steff393** [comment]
Hallo @hackicodi, nein, das ist leider nicht möglich.
