### ISSUE TITLE
Timeout beim Überschussladen

### ISSUE THREAD

**Issue by istmichseegal** [steff393/wbec#71]
Autos mögen es nicht so besonders wenn sie häufig ein- und ausgeschaltet werden. Wie wäre es mit einem konfigurierbaren Timout sodass eine Freischaltung bei PV Überschuss mindestens z.B. 15min dauert.

**Comment by steff393** [comment]
Habe dafür jetzt gerade den Parameter cfgPvMinTime eingebaut:
uint8_t  cfgPvMinTime;                // PV charging: Minimum activation time (in minutes), 0 to disable

Interessant wäre aber noch ein Beleg für "Autos mögen es nicht so besonders wenn sie häufig ein- und ausgeschaltet werden." 
Ist das wirklich so?

**Comment by istmichseegal** [comment]
Klar "mögen" ist natürlich eine vermenschlichung der Maschine. Aber man muss immer bedenken, dass bei jedem einschalten entsprechende Systeme erst starten, Relais intern einschalten und erst dann der Ladevorgang beginnt. Mein i3 braucht z.B. immer ca. 30s bis der Ladevorgang beginnt nach der Freigabe. Relais haben auch nur eine gewisse Menge an Schaltspielen (Lebensdauer). Deswegen denke ich, dass es sinnvoll ist immer eine gewisse Zeit zu Laden bevor wieder abgeschaltet wird unabhängig vom Überschuss. Bei wechselnder Bewölkung kann dies sonst nämlich zu ständigem ein- bzw. Ausschalten führen
