### ISSUE TITLE
Statische IP ohne DHCP

### ISSUE THREAD

**Issue by istmichseegal** [steff393/wbec#72]
Es sollte möglich sein in der Konfiguration eine statische IP vorzugeben.

Beispiel:
https://github.com/zhouhan0126/WIFIMANAGER-ESP32/blob/master/examples/AutoConnectWithStaticIP/AutoConnectWithStaticIP.ino

**Comment by steff393** [comment]
Ja, ist in wbecLan ist das möglich

**Comment by steff393** [comment]
Der nötige Parameter ist 
char     cfgWbecIp[16];               // stat. IP address for wbec, "" to disable 
Also z.B. "cfgWbecIp":"192.168.123.123"

**Comment by istmichseegal** [comment]
Danke
