### ISSUE TITLE
web page access problems via mesh repeater

### ISSUE THREAD

**Issue by gitMichael** [steff393/wbec#8]
I have almost no webpage access over a mesh repeater WLAN hotspot but no problems with direct mesh router connection (same WLAN). Ping works only sometimes, DHCP works. Where try searching first?

**Comment by steff393** [comment]
Good question, this is new... Looks not directly related to wbec, but to ESP8266 in general. Do you have the same issue also with other ESP sketches? Maybe the ESP still recognizes the mesh router and tries connecting to it even if the signal is worse than the one of the mesh repeater?
You could remove the following lines in main.cpp
```
  WiFiManager wifiManager;
  char ssid[32]; strcpy(ssid, cfgApSsid);
  char pass[63]; strcpy(pass, cfgApPass);
  wifiManager.autoConnect(ssid, pass);
```
and replace them with a simple
```
    WiFi.mode(WIFI_STA);
    WiFi.begin();
```

But you need to `#include <ESP8266WiFi.h>`in addition and have your Wifi credentials already entered before.

Is it possible to access the x.x.x.x/json and see the wifi.signal value?
