### ISSUE TITLE
Konfiguration maximale Strommenge

### ISSUE THREAD

**Issue by lawilfried** [steff393/wbec#80]
Auf Seite 5 der wbec-Anleitung.md wird im Abschnitt "Schaltereinstellung in der Wallbox" u. a. festgelegt: "S2: 0000". Es wird auch auf die Originalanleitung der Wallbox verwiesen, dort steht im Abschnitt 1.6.6, dass die Einstellung 0000 10 A maximale Strommenge im System bedeute. Bei einer 11kw-Wallbox würde mir die Einstellung 0001 (die 1 für S2/4) eher einleuchten, weil dies 16 A entspricht. 
Ich habe 2 Wallboxen und momentan bei beiden "S2: 0000" eingestellt. Das funktioniert auch soweit, ich bin mir aber nicht sicher, ob ich damit nicht zu wenig "maximale Strommenge im System" zur Verfügung stelle.
PS: Ich schreibe dieses Issue auch deshalb, weil die Mailadresse von Stefan (wbec393@gmail.com)  seit geraumer Zeit nicht erreichbar ist: Undelivered Mail Returned to Sender.

**Comment by steff393** [comment]
Hallo lawilfried,
wenn die Wallbox als Follower eingestellt ist, dann ist die Bedeutung von S2 **nicht** die "maximale Strommenge im System", sondern die "Konfiguration Bus-ID16".
In Kombination mit wbec muss S2 immer 0000 sein. Einzige Ausnahme: Wenn jemand wbec mit 16 Wallboxen betreibt, dann muss S2=0001 sein.

Habe heute 10 Mails über wbec393@gmail.com bekommen. Im Juni bislang über 150. Es sollte also schon gehen. Vielleicht ist ein Anhang die Ursache?

**Comment by lawilfried** [comment]
Hallo steff393,
ok, da habe ich wohl in der Originalanleitung der Wallbox beim lokalen statt beim externen Lastmanagement geschaut.-
Ich habe dir eine Testmail ohne Anhang gesendet: Mail delivery failed: returning message to sender.

**Comment by lawilfried** [comment]
Nach genauerer Betrachtung der Meldungen in "Mail delivery failed ..." liegt wohl das hier beschriebene Problem zugrunde: https://www.tec-bite.ch/warum-mag-google-meine-mails-nicht/

**Comment by steff393** [comment]
Ja, das wird immer schlimmer...
