### ISSUE TITLE
Problems with config

### ISSUE THREAD

**Issue by maggz1506** [steff393/wbec#86]
Hello,

i need help with installation.
My config is as followed:
wbecpro - heidelberg energy control - evcc on windows - while installation i get following message while configure wallbox:
cannot create charger 'heidelberg': dial tcp 192.168.178.139:502: connectex: No connection could be made because the target machine actively refused it.

can someone help me?

**Comment by steff393** [comment]
Hello,
the configuration is described in the wiki: https://github.com/steff393/wbec/wiki/Configuration-Example:-EVCC-via-MQTT

Important: It's not necessary to configure wbec in evcc as 'heidelberg'.
