### ISSUE TITLE
Neues Webgui über Firmware oder nur über data.zip?

### ISSUE THREAD

**Issue by emmrichd** [steff393/wbec#87]
Hallo,

bevor ich mein System kaputt flashe:
Verstehe ich das richtig, dass die Firmware alleine die Webgui nicht aktualisiert?
Dazu muss ich den Inhalt der data.zip hochladen?
Und der ist für alle wbec-Ausführungen gleich?
Und meine cfg.json bleibt unverändert?

Viele Grüße, Dieter

**Comment by steff393** [comment]
Hallo Dieter,
ja, du musst über http://wbec.local/edit die Dateien einzeln hochladen. Diese Dateien (html, css, js) sind für alle Varianten gleich. Das Ladelog ist derzeit aber nur in den Fertigvarianten verfügbar. 
Die cfg.json ist davon nicht betroffen.
