### ISSUE TITLE
cfgPvHttp* Werte werden noch nicht verwendet.

### ISSUE THREAD

**Issue by alocinb** [steff393/wbec#88]
Hallo, kann sein das die Werte cfgPvHttp* noch nicht in der Version 4.9 vorhanden sind ?
bzw programmiert/verwendet worden sind?

Gruß
NIBO

**Comment by steff393** [comment]
Hi, die Werte sind aktuell nur in 1.4.9 und 2.4.9 enthalten (für die Fertigvarianten von wbec).

**Comment by alocinb** [comment]
Ach sooo, jetzt habe ich es verstanden! na ja, wenn es hier um Geld geht, dann brauche ich nicht mehr Fehler suchen, sondern überlasse ich dir die Fehler suche in Zukunft lieber.
was kostet aktuell so ein wbecPro ?
Gruß
NIBO
