### ISSUE TITLE
Verbesserungsvorschlag 2: cfgMqttWattJson einfacher eingeben.

### ISSUE THREAD

**Issue by alocinb** [steff393/wbec#90]
https://github.com/steff393/wbec/blame/b702a9e48b1000780891ef55d1aaa81b2c3bad4c/src/mqtt.cpp#L138

pch = strstr(buffer, cfgMqttWattJson) + strlen(cfgMqttWattJson)+2;

zu der Länge einfach +2 dazu, damit muss keiner mehr an \":  denken :-)

Gruß
NIBO

**Comment by steff393** [comment]
Dafür müsste dann aber auch immer ein ": (bzw. 2 beliebige Zeichen) an der durchsuchten Stelle stehen --> schränkt die Flexibilität unnötig ein :-)

**Comment by alocinb** [comment]
Aber ein Json Keyword endet immer mit ":
Oder habe ich was falsch verstanden ? 
http://json-schema.org/
