### ISSUE TITLE
Neue Installation - Unterschiedliche Spannungen an "voltL1","voltL2" und "voltL3"

### ISSUE THREAD

**Issue by aLEXXqu** [steff393/wbec#91]
Hallo,

ich  habe WBEC neu mit einer Heidelberg Energy Control installiert. Das Problem ist, dass ich aktuell ohne das bisher ein Auto angeschlossen war, folgende Werte für die drei Phasen bekomme:
"voltL1":190,"voltL2":265,"voltL3":261
Was habe ich bisher gemacht:
- Alle Kabel sind durchgemessen und in Ordnung
- zwischen dem Neutralleiter und den Phasen liegen 234 V und zwischen den Phase 406V gemessen jeweils im Schaltschrank und an den Anschlüssen der Box
- Gleiche Werte bei Anschluss über WLAN als auch DLAN
- Wallbox einmal getauscht

Würdet ihr da ein Auto ranhängen?

Danke und Gruß,
Alex

**Comment by steff393** [comment]
Off-topic, nicht durch wbec verursacht.
