### ISSUE TITLE
Die neue Webgui zeigt Update Option auf wbecLan

### ISSUE THREAD

**Issue by hpoeppel** [steff393/wbec#92]
Die neue Webgui zeigt auf dem wbecLan einen Update Button, der aber nicht funktioniert. 

Fehlermeldung ist "FileNotFound" in der Data.zip ist auch keine Datei dafür enthalten.

Installierte Version ist 2.4.9

**Comment by alocinb** [comment]
Hallo, siehtst du über Edit ob es eine Datei gibt = cfg.json ?

**Comment by steff393** [comment]
Ja, das ist ein bekanntes Verhalten: wbecLan kann nur mittels curl-Befehl aktualisiert werden (s. Seite 10 in der Anleitung). Daher führt dieser Link bei wbecLan ins Leere.
Der Einfachheit halber (um keine unterschiedlichen Dateien für das WebInterface zu haben) habe ich aber keine Spezialbehandlung eingefügt. Dies wird auch so bleiben.
