### ISSUE TITLE
Feature Request: Show float values in current locale formatting (e.g. "2.030,51" instead of "2030.51"

### ISSUE THREAD

**Issue by kalwados** [steff393/wbec#93]
As of V0.4.9, float values in the main screen `web.html` are formatted with US/English locale settings, using a dot (point) as decimal separator. For values greater that 999 there is no thousand seperator.

My proposal is to make use of the current locale settings from the browser, using `value.toLocaleString()` .

**Comment by steff393** [comment]
Done :-)
