### ISSUE TITLE
Wbec Nutzung für andere wallboxen mit rs485

### ISSUE THREAD

**Issue by mmoeller53** [steff393/wbec#94]
Hallo,
habe ein wbec Kit im Einsatz mit meiner Heidelberg wallbox,
Diese bietet ja leider kein automatisches umschalten zu 1 phasigem laden.

Habe nun die wallbox vom lidel gekauft, diese läd 1phasig oder 3 phasig je nach Anschluss, dies erkennt die wallbox selbst.

Zudem hat sie einen rs485 Anschluss für Lastmanagement.
Kann man diesen nutzen z.b. mit wbec um automatisch den Ladestrom einzustellen?

Das würde mir eine Menge Arbeit sparen, falls jemand eine Idee dazu hat gerne mitteilen.

**Comment by steff393** [comment]
Für die Lidl Wallbox gibt es leider keine Doku des RS485-Protokolls.
