### ISSUE TITLE
Missing howto connection ESP<->Modbus

### ISSUE THREAD

**Issue by selbstmacher** [steff393/wbec#95]
I have searched every Issue and website regarding wbec, but I haven't found any information on how to connect the ESP to the modbus.
Have I missed something essential here or was this information taken from the project site because there are now ready to use modules?

I found one picture showing an adapter that was connected to the esp but had no electronic parts, but only the connector for modbus.
So it should be possible to connect the ESP directly to modbus or am I totally wrong?

**Comment by steff393** [comment]
Hi, 
yes, questions regarding the hardware will not be supported here, due to the availability of ready-to-use modules. Sorry, but this is causing a lot of support efforts, which is unnecessary because with the modules it works right out of the box. Feel free to contact me via wbec393@gmail.com
